---
- name: Create view with one zone variant
  hosts: localhost
  gather_facts: false
  collections:
    - helvascale.helva_powerdns_ansible
  tasks:
    - name: Ensure internal view exists with one zone variant
      powerdns_view:
        name: internal
        mode: add
        zone_variants:
          - example.org..internal
        state: present
        pdns_host: powerdns.example.org
        pdns_prot: https
        strict_ssl_checking: true
        pdns_api_key: "{{ vault_pdns_api_key }}"
